blacklist = ["scratch"]

dir_length = 2  # Uses last 2 directories: "projects/sesh" instead of just "sesh"

[default_session]
#startup_command = "nvim -c ':Telescope find_files'"
preview_command = "ls {}"

[[session]]
name = "dotfiles"
path = "~/dot"
startup_command = "nvim -c ':Telescope find_files'"
preview_command = "ls {}"

[[session]]
name = "projects"
path = "~/prj"
startup_command = "ls"
windows = [ 'opencode' ]

[[window]]
name = "opencode"
startup_script = "opencode"

[[window]]
name = "claude"
startup_script = "claude"

[[window]]
name = "git"
startup_script = "git pull"

[[wildcard]]
pattern = "~/prj/**"
startup_command = "git status"
preview_command = "git status"
