add_newline = false
palette = 'catppuccin_mocha'
format = '$time$directory$character'
right_format = '$all'

[time]
disabled = false
format = '[$time]($style) '
time_format = '%R'
use_12hr = false
utc_time_offset = "local"
time_range = "-"

[hostname]
ssh_only = true
format = '[$ssh_symbol](bold blue) @ [$hostname](bold red)'

[character]
success_symbol = "[»](bold green) "
error_symbol = "[✗](bold red) "
vicmd_symbol = "[«](bold green) "

[directory]
format = "[$path]($style) [$read_only]($read_only_style) "
read_only = " 󰌾"

[aws]
symbol = '☁️ '
style = 'peach'
disabled = true
format = '[$symbol($profile )(\($region\) )]($style)'

[git_branch]
symbol = '🌱 '
style = 'mauve'
format = '[$symbol$branch(:$remote_branch)]($style) '

[golang]
symbol = '🐹 '
style = 'teal'
format = '[$symbol$version]($style) '

[docker_context]
symbol = '🐳 '
format = 'via [🐋 $context](blue bold)'

[kubernetes]
symbol = '⚙️ '
style = 'sapphire'
disabled = false
#format = '[$symbol$context( \($namespace\))]($style) '
format = '[$symbol$context]($style) '

[[kubernetes.contexts]]
context_pattern = "teleport\\.(?P<region>[\\w-]+)\\..*fleetops.*"
context_alias	= "$region (fleetops)"
style = "bold yellow"

[[kubernetes.contexts]]
context_pattern = "teleport\\.(?P<region>[\\w-]+)\\..*mgmt.*"
context_alias	= "$region (mgmt)"
style = "bold purple"

[[kubernetes.contexts]]
context_pattern = "teleport\\.(?P<region>[\\w-]+)\\..*?-(?P<cluster>.*)"
context_alias = "$region ($cluster)"
style = "blue"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
