add_newline = false
palette = 'catppuccin_mocha'
format = '$directory$character'
right_format = '$all'

[hostname]
ssh_only = true
format = '[$ssh_symbol](bold blue) @ [$hostname](bold red)'

[aws]
symbol = '☁️ '
style = 'peach'
disabled = false
format = '[$symbol($profile )(\($region\) )]($style)'

[git_branch]
symbol = '🌱 '
style = 'mauve'
format = '[$symbol$branch(:$remote_branch)]($style) '

[golang]
symbol = '🐹 '
style = 'teal'
format = '[$symbol$version]($style) '

[docker_context]
symbol = '🐳 '
format = 'via [🐋 $context](blue bold)'

[kubernetes]
symbol = '⚙️ '
disabled = false
style = 'sapphire'
detect_files = ['k8s']
format = '[$symbol$context( \($namespace\))]($style) '

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
