#!/bin/sh

#----------------------------------------------------------------------
# Path Exports
#----------------------------------------------------------------------
export PATH=$HOME/bin:$PATH
export PATH=$HOME/.local/bin:$PATH
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$HOME/go/bin
