require("ahmza/vars")

require("ahmza/autostart")
require("ahmza/behaviour")
require("ahmza/visual")
require("ahmza/keybinds")
require("ahmza/monitors")
require("ahmza/input")
require("ahmza/window-rules")
require("ahmza/workspace-rules")
